### ISSUE TITLE
Multi file anglular.flat structure not working as it should

### ISSUE THREAD

**Issue by jbozic1** [ppatotski/vscode-app-localizer#23]
Hi, 
I'm using ngx-translate for loading translations, and it works wit angular.flat structure of file. When is configure it in applocalizer.json, i just have bunch of errors even translations exists in all files.
`{
	"validator": {
		"multiFile": true,
		"filePathPattern": "**/*.locale.json",
		"fileStructure": "angular.flat"
	},
	"pseudoLocale": {
		"expander": 0.3,
		"wordexpander": 0.5,
		"exclamations": true,
		"brackets": true,
		"accents": true,
		"rightToLeft": false,
		"escapeCharacters": false
	}
}`

Errors i get:
Label "0" is missing in "en.locale, de.locale" locale(s)
Label "1" is missing in "en.locale, de.locale" locale(s)
Label "2" is missing in "en.locale, de.locale" locale(s)
Label "3" is missing in "en.locale, de.locale" locale(s)
Label "4" is missing in "en.locale, de.locale" locale(s)
...Thats for only one key:value in json..
When i put all translations in polymer structure extension works great, but app doesn't read that translations since they are not in root.

**Comment by ppatotski** [comment]
Can I see locale file?

**Comment by jbozic1** [comment]
en.locale.json:
```
{
    "Hello": "Hello"
}
```
de.locale.json:
```
{
    "Hello": "halo"
}
```

As soon as i change structure to:
```
{
    "en" : {
        "Hello": "halo"
    } 
}
```
and file structure to polymer it works great.

**Comment by ppatotski** [comment]
Thanks. I will look at this issue closely. Meanwhile, can you try to remove locale word from file names and see if it works? It seems I have unit test for that case.

**Comment by jbozic1** [comment]
Nope, nothing helps.

**Comment by ppatotski** [comment]
Do you have any other files in your folder?

**Comment by jbozic1** [comment]
No, just en.locale.json and de.locale.json

**Comment by ppatotski** [comment]
Maybe not in the same folder, could be other folder that match `**/*.locale.json` pattern. Can you try to reduce scope of pattern e.g. `/mylocales/*.locale.json`. I am having hard time to reproduce this issue locally. Or maybe hidden files are generated.

**Comment by jbozic1** [comment]
<img width="1593" alt="screen shot 2018-03-09 at 20 56 53" src="https://user-images.githubusercontent.com/8434968/37227153-8d08a7c4-23dc-11e8-989d-0c1102684338.png">

**Comment by jbozic1** [comment]
```
{
	"validator": {
		"multiFile": true,
		"filePathPattern": "**/locales/*.locale.json",
		"fileStructure": "angular.flat"
	}
```
That doesn't help. It figures out location very good

**Comment by ppatotski** [comment]
Thanks, I think I am starting getting it. It is probably a combination of issues. Try also `/src/locales/*.locale.json`

**Comment by jbozic1** [comment]
When I put it's whole path `/src/assets/locales/*.locale.json` it doesn't work at all, there is no error.

**Comment by jbozic1** [comment]
Location shouldn't be problem in my opinion because when i use polymer file structure it works good.

**Comment by ppatotski** [comment]
I released a fix for it. Let me know if you still have any issues.

**Comment by jbozic1** [comment]
It works now. Thank you very much! This was fast
